services:
  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./garagesale:/app/garagesale
      - ./items:/app/items
      - ./media:/app/media
      - ./static:/app/static
      - ./templates:/app/templates
      - ./db.sqlite3:/app/db.sqlite3
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
