apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "garagesale.labels" . | nindent 4 }}
  name: {{ include "garagesale.fullname" . }}-garagesale
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deployment: garagesale
    {{- include "garagesale.selectorLabels" . | nindent 4 }}
  type: ClusterIP
