# Generated by Django 4.2.16 on 2024-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='itemlink',
            name='name',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='market/'),
        ),
    ]
