env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_SCAN_SUGGEST: false
name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select the environment
        type: environment
jobs:
  build-docker-image:
    environment: ${{ inputs.environment }}
    name: Build backend docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata for docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/backend
        tags: |
          type=raw,value=${{ vars.DOCKER_IMAGE_TAG }}

    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: backend
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  install-helm-chart-and-run-updates:
    environment: ${{ inputs.environment }}
    name: Install helm chart
    needs:
    - build-docker-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup kube tools
      uses: yokawasa/action-setup-kube-tools@v0.11.1
      with:
        setup-tools: |
          helm
          kubectl

    - name: Create kube config
      run: |
        mkdir ${HOME}/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ${HOME}/.kube/config
        chmod 400 ${HOME}/.kube/config

    - name: Install helm chart
      run: |
        helm upgrade garagesale chart \
          --install \
          --namespace ${{ vars.KUBERNETES_NAMESPACE }} \
          --values etc/${{ inputs.environment }}/values.yaml

    - name: Rollout restart workloads
      run: |
        kubectl rollout restart deployment \
        --namespace ${{ vars.KUBERNETES_NAMESPACE }} \
        --selector='restart-on-deploy=true'

  tag:
    name: Tag
    needs:
    - install-helm-chart-and-run-updates
    runs-on: ubuntu-latest
    steps:
    - name: Advance the environment tag
      uses: actions/github-script@v7
      with:
        script: |
          try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/${{ inputs.environment }}",
              });
          } catch (e) {
            console.log("The ${{ inputs.environment }} tag doesn't exist yet: " + e);
          }
          
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ inputs.environment }}",
            sha: context.sha,
          });
